version: "3"

services:

  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app-tier


  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    tty: true


  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - ./frontend:/usr/src/app/static_files
    depends_on:
      - frontend
      - backend
    networks:
      - app-tier


networks:
  app-tier:
    driver: bridge
