version: "3"

services:

  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - app-tier


  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    tty: true


  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - build_folder:/var/www/frontend
    depends_on:
      - frontend
      - backend
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
