name: Deploy Project

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  build:
    runs-on: Amazon Linux 2 AMI

    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.PASSWORD }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          port: ${{ secrets.PORT }}
          script: ${{ secrets.SCRIPT }}
